
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FERNANDO
 */
public class JPCreateUser extends javax.swing.JPanel {

    /**
     * Creates new form JPCreateUser
     */
    public JPCreateUser(javax.swing.JPanel contenedor) {
        this.contenedor=contenedor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtVPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        btnCrear = new javax.swing.JButton();
        lbMessageIncorecPass = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(570, 360));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(58, 180, 180));
        jLabel1.setText("CREACION DE USUARIO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(58, 180, 180));
        jLabel2.setText("Correo: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(58, 180, 180));
        jLabel3.setText("Nombre: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(58, 180, 180));
        jLabel4.setText("Apellido: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        txtName.setForeground(new java.awt.Color(102, 102, 102));
        txtName.setText("Ingrese Nombre");
        txtName.setBorder(null);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 160, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 190, 10));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/name-20.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 20, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/name-20.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 20, 20));

        txtLastName.setForeground(new java.awt.Color(102, 102, 102));
        txtLastName.setText("Ingrese Apellido");
        txtLastName.setBorder(null);
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 160, 20));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 190, 10));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/mail-20.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 20, 20));

        txtMail.setForeground(new java.awt.Color(102, 102, 102));
        txtMail.setText("Ingrese Correo");
        txtMail.setBorder(null);
        add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 160, 20));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 190, 10));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(58, 180, 180));
        jLabel8.setText("Usuario: ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconUser-25.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 20, 20));

        txtUser.setForeground(new java.awt.Color(102, 102, 102));
        txtUser.setText("Ingrese Usuario");
        txtUser.setBorder(null);
        add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 160, 20));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 190, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(58, 180, 180));
        jLabel10.setText("Contraseña: ");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconKey-30.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 20, 20));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 190, 10));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(58, 180, 180));
        jLabel12.setText("Repetir Contraseña: ");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconKey-30.png"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 20, 20));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 190, 10));

        txtVPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtVPassword.setText("jPasswordField1");
        txtVPassword.setBorder(null);
        add(txtVPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 160, 20));

        txtPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtPassword.setText("jPasswordField1");
        txtPassword.setBorder(null);
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 160, 20));

        btnCrear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(58, 180, 180));
        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/save-60.png"))); // NOI18N
        btnCrear.setToolTipText("");
        btnCrear.setContentAreaFilled(false);
        btnCrear.setDefaultCapable(false);
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearMouseExited(evt);
            }
        });
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 210, 60));

        lbMessageIncorecPass.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbMessageIncorecPass.setForeground(new java.awt.Color(238, 131, 88));
        lbMessageIncorecPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lbMessageIncorecPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 170, 20));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/back-40.png"))); // NOI18N
        btnBack.setContentAreaFilled(false);
        btnBack.setDefaultCapable(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseEntered
        // TODO add your handling code here:
        btnCrear.setText("CREAR USUARIO");
    }//GEN-LAST:event_btnCrearMouseEntered

    private void btnCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseExited
        // TODO add your handling code here:
        btnCrear.setText("");
    }//GEN-LAST:event_btnCrearMouseExited

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        String password = txtPassword.getText();
        if(password.equals(txtVPassword.getText())){
            lbMessageIncorecPass.setVisible(false);
            String[] name = {txtName.getText()+txtLastName.getText(),txtName.getText(),txtLastName.getText(),txtMail.getText(),txtUser.getText(),password};
            try{
                Connection my_connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+BaseDatos+"?serverTimezone=UTC", "PROYECTO_PPR", "Fernando1999");
                Statement my_statement = my_connection.createStatement();
                my_statement.execute("INSERT INTO "+Tabla+" VALUE ('"+name[0]+"','"+name[1]+"','"+name[2]+"','"+name[3]+"','"+name[4]+"','"+name[5]+"')");
                JOptionPane.showMessageDialog(null,"EL USUARIO SE CREO CORRECTAMENTE\nNombre: "+name[1]+"\nApellido: "+name[2],"CORRECTO",JOptionPane.INFORMATION_MESSAGE);
                my_connection.close();
                CardLayout carta = (CardLayout)contenedor.getLayout();
                carta.show(contenedor, idPresentacion);
            }catch(SQLException e){
                System.out.println("Error: "+e.getMessage());
            }
            
        }else{
            lbMessageIncorecPass.setVisible(true);
            lbMessageIncorecPass.setText("CONTRASEÑAS NO COINCIDEN");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout carta = (CardLayout)contenedor.getLayout();
        carta.show(contenedor, idPresentacion);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbMessageIncorecPass;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    private javax.swing.JPasswordField txtVPassword;
    // End of variables declaration//GEN-END:variables
    private final String BaseDatos = "PROYECTOPPR";
    private final String Tabla = "REGISTROUSUARIO";
    private javax.swing.JPanel contenedor;
    private final static String idPresentacion = "laminaPresentacion";
}
