/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiTablas;

import complementos.ModeloOpc;
import complementos.RunTableOpc;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FERNANDO
 */
public class JPTableOpcFacebook extends javax.swing.JPanel {
    DefaultTableModel modelTableFacebook;
    /**
     * Creates new form JPTableOpcFacebook
     */
    private RunTableOpc table;
    public JPTableOpcFacebook() {
        initComponents();
        table = new RunTableOpc(jtOpcFacebook,"registroconsultafacebook");
    }
    public RunTableOpc getTable() {
        return table;
    }

    public void setTable(RunTableOpc table) {
        this.table = table;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtOpcFacebook = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtOpcFacebook.setBackground(new java.awt.Color(255, 255, 255));
        jtOpcFacebook.setForeground(new java.awt.Color(58, 180, 180));
        jtOpcFacebook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtOpcFacebook);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 260));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtOpcFacebook;
    // End of variables declaration//GEN-END:variables
}
