/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiTablas;

import complementos.ModeloOpcTwitter;
import complementos.MySqlConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FERNANDO
 */
public class JPTableOpcTwitter extends javax.swing.JPanel {
    DefaultTableModel modeloTableTwitter;
    /**
     * Creates new form JPTableOpcTwitter
     */
    public JPTableOpcTwitter() {
        initComponents();
    }
    
    public void startTable(){
        modeloTableTwitter = new DefaultTableModel();
        String columnas[] = {"Id","User Id"};
        modeloTableTwitter.setColumnIdentifiers(columnas);     
        try {
            setDatosTabla(cargarDatosArreglo ());
        } catch (SQLException e) {
            System.out.println("Error SQLException JPTableOpcTwitter: "+e.getMessage());
        }
    }
    
    private ArrayList<ModeloOpcTwitter> cargarDatosArreglo () throws SQLException{
        ArrayList<ModeloOpcTwitter> arreglo = new ArrayList<ModeloOpcTwitter>();
        String url = "SELECT * FROM registroconsultatwitter";
        Connection my_connection = null;
        Statement my_statement = null;
        ResultSet my_resultSet = null;
        
        try{
            my_connection = (new MySqlConnection()).conetMysql();
            my_statement = my_connection.createStatement();
            my_resultSet = my_statement.executeQuery(url);
            while(my_resultSet.next()){
                ModeloOpcTwitter temp = new ModeloOpcTwitter();
                temp.setId(my_resultSet.getString("id"));
                temp.setIdUser(my_resultSet.getString("registrousuario_idUsuario"));
                arreglo.add(temp);
            }
            return arreglo;
        }catch(SQLException e){
            System.out.println("Error SQLException cargarDatosArreglo: "+e.getMessage());
        }finally{
            if(my_connection!=null)my_connection.close();
            if(my_statement!=null)my_statement.close();
        }
        return arreglo;
    }
    
    private void setDatosTabla (ArrayList<ModeloOpcTwitter> datos){
        modeloTableTwitter.setRowCount(0);
        Object o[] = new Object[modeloTableTwitter.getColumnCount()];
        for(ModeloOpcTwitter e:datos){
            o[0] = e.getId();
            o[1] = e.getIdUser();
            modeloTableTwitter.addRow(o);
        }
        jtOpcTwitter.setModel(modeloTableTwitter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtOpcTwitter = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jtOpcTwitter.setForeground(new java.awt.Color(58, 180, 180));
        jtOpcTwitter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtOpcTwitter);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 260));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtOpcTwitter;
    // End of variables declaration//GEN-END:variables
}
