/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiTablas;

import complementos.ModeloFacebook;
import complementos.ModeloTwitter;
import complementos.MySqlConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FERNANDO
 */
public class JPTableDateFacebook extends javax.swing.JPanel {

    /**
     * Creates new form JPTableDateFacebook
     */
    public JPTableDateFacebook() {
        initComponents();
    }
    
    public void startTable(){
        modeloTableFacebook = new DefaultTableModel();
        String columnas[] = {"post_id","text","time","image","images","likes","comments","shares","post_url","link"};
        modeloTableFacebook.setColumnIdentifiers(columnas);     
        try {
            setDatosTabla(cargarDatosArreglo ());
        } catch (SQLException e) {
            System.out.println("Error SQLException JPTableOpcTwitter: "+e.getMessage());
        }
    }
    
    public String getValorConsulta() {
        return valorConsulta;
    }

    public void setValorConsulta(String valorConsulta) {
        this.valorConsulta = valorConsulta;
    }
    
    private ArrayList<ModeloFacebook> cargarDatosArreglo () throws SQLException{
        ArrayList<ModeloFacebook> arreglo = new ArrayList<ModeloFacebook>();
        String QUERRY = "SELECT * FROM registrofacebook WHERE registroconsultaFacebook_id = "+valorConsulta;
        Connection my_connection = null;
        Statement my_statement = null;
        ResultSet my_resultSet = null;
        
        try{
            my_connection = (new MySqlConnection()).conetMysql();
            my_statement = my_connection.createStatement();
            my_resultSet = my_statement.executeQuery(QUERRY);
            while(my_resultSet.next()){
                
                String post_id = my_resultSet.getString("post_id");
                String text = my_resultSet.getString("text");
                String time = my_resultSet.getString("time");
                String image = my_resultSet.getString("image");
                String images = my_resultSet.getString("images");
                String likes = my_resultSet.getString("likes");
                String comments = my_resultSet.getString("comments");
                String shares = my_resultSet.getString("shares");
                String post_url = my_resultSet.getString("post_url");
                String link = my_resultSet.getString("link");
                
                String registrousuario_idUsuario = String.valueOf(my_resultSet.getInt("registroconsultaFacebook_id"));
                arreglo.add(new ModeloFacebook(post_id,text,time,image,images,likes,comments,shares,post_url,link,registrousuario_idUsuario));
            }
            return arreglo;
        }catch(SQLException e){
            System.out.println("Error SQLException cargarDatosArreglo: "+e.getMessage());
        }finally{
            if(my_connection!=null)my_connection.close();
            if(my_statement!=null)my_statement.close();
        }
        return arreglo;
    }
    
    private void setDatosTabla (ArrayList<ModeloFacebook> datos){
        modeloTableFacebook.setRowCount(0);
        Object o[] = new Object[modeloTableFacebook.getColumnCount()];
        for(ModeloFacebook e:datos){
            o[0] = e.getPost_id();
            o[1] = e.getText();
            o[2] = e.getTime();
            o[3] = e.getImage();
            o[4] = e.getImages();
            o[5] = e.getLikes();
            o[6] = e.getComments();
            o[7] = e.getShares();
            o[8] = e.getPost_url();
            o[8] = e.getLink();
            modeloTableFacebook.addRow(o);
        }
        jtDateFacebook.setModel(modeloTableFacebook);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtDateFacebook = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtDateFacebook.setBackground(new java.awt.Color(255, 255, 255));
        jtDateFacebook.setForeground(new java.awt.Color(58, 180, 180));
        jtDateFacebook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtDateFacebook);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 230));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtDateFacebook;
    // End of variables declaration//GEN-END:variables
    private String valorConsulta;
    private DefaultTableModel modeloTableFacebook;
}
