
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FERNANDO
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        this.setLocationRelativeTo(null);
        my_connection = null;
        
        laminaAdd = new jpAdd("CREAR NUEVO USUARIO",new btnAddActionPerformed());
        laminaPresentacion = new jpPresentacion();
        laminaDelect = new jpDelectUser();
        laminaReport = new jpReport();
        laminaModify = new jpAdd("MODIFICAR USUARIO",null);
        
        jpContentPrimary.setLayout(new CardLayout(0,0));
        jpContentPrimary.add(laminaPresentacion,idPresent);
        jpContentPrimary.add(laminaAdd,idAddUser);
        jpContentPrimary.add(laminaDelect,idDelect);
        jpContentPrimary.add(laminaReport,idReport);
        jpContentPrimary.add(laminaModify,idModify);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpBtn = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbAdd = new javax.swing.JRadioButton();
        rbDelect = new javax.swing.JRadioButton();
        rbModify = new javax.swing.JRadioButton();
        rbShowReport = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSqlConet = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jpContentPrimary = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbAdd.setBackground(new java.awt.Color(255, 255, 255));
        grpBtn.add(rbAdd);
        rbAdd.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        rbAdd.setForeground(new java.awt.Color(58, 180, 180));
        rbAdd.setText("ADD USER");
        rbAdd.setEnabled(false);
        rbAdd.setFocusable(false);
        rbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAddActionPerformed(evt);
            }
        });
        jPanel1.add(rbAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        rbDelect.setBackground(new java.awt.Color(255, 255, 255));
        grpBtn.add(rbDelect);
        rbDelect.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        rbDelect.setForeground(new java.awt.Color(58, 180, 180));
        rbDelect.setText("DELECT USER");
        rbDelect.setEnabled(false);
        rbDelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDelectActionPerformed(evt);
            }
        });
        jPanel1.add(rbDelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        rbModify.setBackground(new java.awt.Color(255, 255, 255));
        grpBtn.add(rbModify);
        rbModify.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        rbModify.setForeground(new java.awt.Color(58, 180, 180));
        rbModify.setText("MODIFY");
        rbModify.setEnabled(false);
        rbModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbModifyActionPerformed(evt);
            }
        });
        jPanel1.add(rbModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        rbShowReport.setBackground(new java.awt.Color(255, 255, 255));
        grpBtn.add(rbShowReport);
        rbShowReport.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        rbShowReport.setForeground(new java.awt.Color(58, 180, 180));
        rbShowReport.setText("SHOW REPORT");
        rbShowReport.setEnabled(false);
        rbShowReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbShowReportActionPerformed(evt);
            }
        });
        jPanel1.add(rbShowReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/report-30.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 30, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/add-30.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 30, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/modify-30.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/deleted-30.png"))); // NOI18N
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 30, 30));

        btnSqlConet.setBackground(new java.awt.Color(255, 255, 255));
        btnSqlConet.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnSqlConet.setForeground(new java.awt.Color(58, 180, 180));
        btnSqlConet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/sql-120.png"))); // NOI18N
        btnSqlConet.setBorderPainted(false);
        btnSqlConet.setContentAreaFilled(false);
        btnSqlConet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSqlConetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSqlConetMouseExited(evt);
            }
        });
        btnSqlConet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqlConetActionPerformed(evt);
            }
        });
        jPanel1.add(btnSqlConet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, 120));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cerrar-30.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 150));

        jpContentPrimary.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpContentPrimaryLayout = new javax.swing.GroupLayout(jpContentPrimary);
        jpContentPrimary.setLayout(jpContentPrimaryLayout);
        jpContentPrimaryLayout.setHorizontalGroup(
            jpContentPrimaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jpContentPrimaryLayout.setVerticalGroup(
            jpContentPrimaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        getContentPane().add(jpContentPrimary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 500, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSqlConetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqlConetActionPerformed
        // TODO add your handling code here:
        try{
            my_connection = DriverManager.getConnection(url, user, password);
            btnSqlConet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/sql-verde-120.png")));
            btnSqlConet.setForeground(new java.awt.Color(68, 209, 125));
            rbAdd.setEnabled(true);
            rbDelect.setEnabled(true);
            rbModify.setEnabled(true);
            rbShowReport.setEnabled(true);
        }catch(SQLException e){
            System.out.println("Error btnSqlConetActionPerformed: "+e.getMessage());
            btnSqlConet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/sql-rojo-120.png")));
            btnSqlConet.setForeground(new java.awt.Color(228, 102, 116));
        }
        
    }//GEN-LAST:event_btnSqlConetActionPerformed

    class btnAddActionPerformed implements ActionListener{
        public void actionPerformed(ActionEvent e){
            if(my_connection != null){
                int DNI = Integer.parseInt(laminaAdd.getTxtDNI().getText());
                String Nombre = laminaAdd.getTxtNombre().getText();
                String Apellido = laminaAdd.getTxtApellido().getText();
                int Edad = Integer.parseInt(laminaAdd.getTxtEdad().getText());
                try {
                    PreparedStatement insert = my_connection.prepareStatement("INSERT INTO USER VALUES (?,?,?,?);");
                    insert.setInt(1, DNI);
                    insert.setString(2, Nombre);
                    insert.setString(3, Apellido);
                    insert.setInt(4, Edad);
                    insert.executeUpdate();
                } catch (SQLException ex) {
                    System.out.println("Error btnAddActionPerformed: "+ex.getMessage());
                }
            }
        }
    }
    
    private void btnSqlConetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSqlConetMouseEntered
        // TODO add your handling code here:
        btnSqlConet.setText("CONET");
    }//GEN-LAST:event_btnSqlConetMouseEntered

    private void btnSqlConetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSqlConetMouseExited
        // TODO add your handling code here:
        btnSqlConet.setText("");
    }//GEN-LAST:event_btnSqlConetMouseExited

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        if(my_connection != null){
            try {
                my_connection.close();
            } catch (SQLException ex) {
                System.out.println("Error my_connection close: "+ex.getMessage());
            }
        }
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void rbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAddActionPerformed
        // TODO add your handling code here:
        CardLayout carta = (CardLayout)jpContentPrimary.getLayout();
        carta.show(jpContentPrimary, idAddUser);
    }//GEN-LAST:event_rbAddActionPerformed

    private void rbDelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDelectActionPerformed
        // TODO add your handling code here:
        CardLayout carta = (CardLayout)jpContentPrimary.getLayout();
        carta.show(jpContentPrimary, idDelect);
    }//GEN-LAST:event_rbDelectActionPerformed

    private void rbShowReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbShowReportActionPerformed
        // TODO add your handling code here:
        CardLayout carta = (CardLayout)jpContentPrimary.getLayout();
        carta.show(jpContentPrimary, idReport);
        laminaReport.StartTable(my_connection);
    }//GEN-LAST:event_rbShowReportActionPerformed

    private void rbModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbModifyActionPerformed
        // TODO add your handling code here:
        CardLayout carta = (CardLayout)jpContentPrimary.getLayout();
        carta.show(jpContentPrimary, idModify);
    }//GEN-LAST:event_rbModifyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnSqlConet;
    private javax.swing.ButtonGroup grpBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpContentPrimary;
    private javax.swing.JRadioButton rbAdd;
    private javax.swing.JRadioButton rbDelect;
    private javax.swing.JRadioButton rbModify;
    private javax.swing.JRadioButton rbShowReport;
    // End of variables declaration//GEN-END:variables
    private final static String idAddUser = "laminaAddUser";
    private final static String idPresent = "laminaPresentacion";
    private final static String idDelect = "laminaDelected";
    private final static String idReport = "laminaReporte";
    private final static String idModify = "laminaModificacion";
    
    
    private jpAdd laminaAdd;
    private jpAdd laminaModify;
    private jpPresentacion laminaPresentacion;
    private jpDelectUser laminaDelect;
    private jpReport laminaReport;
    
    private Connection my_connection;
    private final static String baseDatos = "jdbc";
    private final static String hostname = "localhost";
    private final static String url = "jdbc:mysql://"+hostname+":3306/"+baseDatos+"?serverTimezone=UTC";
    private final static String user = "PROYECTO_PPR";
    private final static String password = "Fernando1999";
}
